#!/bin/bash

TXTDEF='\033[0m'          # everything back to defaults
BAKBLU='\033[37;1;44m'    # blue background
BAKRED='\033[37;1;41m'    # red background
BAKGRN='\033[37;1;42m'    # green background
BLDWHT='\033[0;37;1m'     # bold white text

echo 'Running pre-push tests'

npm run test-cli

if [ $? != 0 ];then
  echo ""
  echo -e "     ${BLDWHT}${BAKRED}  PRE-PUSH TESTS FAILED  ${TXTDEF}"
  echo -e "     ${BLDWHT}${BAKRED}     COMMIT ABORTED      ${TXTDEF}"
  echo ""
  exit 1
fi

exit 0
